# Generated by Django 3.0.8 on 2020-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCompleto', models.CharField(max_length=30)),
                ('DataNascimento', models.DateField()),
                ('TipoTeste', models.CharField(choices=[(1, 'RT-PCR'), (2, 'Sorologia'), (3, 'Teste Rápido'), (4, 'Antígenos'), (5, 'Teste Rápido - Anticorpos')], max_length=60)),
                ('ResultadoTeste', models.CharField(choices=[(1, 'Positivo'), (2, 'Negativo')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
