# Generated by Django 3.0.8 on 2020-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManterPacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ResultadoTeste',
            field=models.IntegerField(choices=[(1, 'Positivo'), (2, 'Negativo')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='TipoTeste',
            field=models.IntegerField(choices=[(1, 'RT-PCR'), (2, 'Sorologia'), (3, 'Teste Rápido'), (4, 'Antígenos'), (5, 'Teste Rápido - Anticorpos')]),
        ),
    ]
